# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/hugoh/pre-commit-fish
    rev: v1.2
    hooks:
      - id: fish_syntax
      - id: fish_indent

  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.17.0
    hooks:
      - id: gitlint
        args: [--contrib=CT1, --ignore=B6, --msg-filename]
